version: '3.8'

services:
  api:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: library_api
    ports:
      - "8000:8000"
    volumes:
      - type: bind
        source: .
        target: /app
    environment:
      - DATABASE_URL=sqlite:///./data/library.db
      - SECRET_KEY=09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    restart: unless-stopped
    networks:
      - library_network

networks:
  library_network:
    name: library_network
    driver: bridge

volumes:
  library_data:
    driver: local
